// Top 25 dishes per cuisine — used by the image search script
// Format: { nameEnglish, nameLocal, nameRomanized }

export interface DishEntry {
  nameEnglish: string
  nameLocal: string
  nameRomanized: string
}

export const CUISINES: Record<string, { country: string; dishes: DishEntry[] }> = {
  korean: {
    country: 'South Korea',
    dishes: [
      { nameEnglish: 'Bibimbap', nameLocal: '비빔밥', nameRomanized: 'Bibimbap' },
      { nameEnglish: 'Kimchi Jjigae', nameLocal: '김치찌개', nameRomanized: 'Kimchi Jjigae' },
      { nameEnglish: 'Bulgogi', nameLocal: '불고기', nameRomanized: 'Bulgogi' },
      { nameEnglish: 'Japchae', nameLocal: '잡채', nameRomanized: 'Japchae' },
      { nameEnglish: 'Tteokbokki', nameLocal: '떡볶이', nameRomanized: 'Tteokbokki' },
      { nameEnglish: 'Samgyeopsal', nameLocal: '삼겹살', nameRomanized: 'Samgyeopsal' },
      { nameEnglish: 'Sundubu Jjigae', nameLocal: '순두부찌개', nameRomanized: 'Sundubu Jjigae' },
      { nameEnglish: 'Haemul Pajeon', nameLocal: '해물파전', nameRomanized: 'Haemul Pajeon' },
      { nameEnglish: 'Dakgalbi', nameLocal: '닭갈비', nameRomanized: 'Dakgalbi' },
      { nameEnglish: 'Kalguksu', nameLocal: '칼국수', nameRomanized: 'Kalguksu' },
      { nameEnglish: 'Jajangmyeon', nameLocal: '짜장면', nameRomanized: 'Jajangmyeon' },
      { nameEnglish: 'Galbitang', nameLocal: '갈비탕', nameRomanized: 'Galbitang' },
      { nameEnglish: 'Bossam', nameLocal: '보쌈', nameRomanized: 'Bossam' },
      { nameEnglish: 'Sundae', nameLocal: '순대', nameRomanized: 'Sundae' },
      { nameEnglish: 'Hotteok', nameLocal: '호떡', nameRomanized: 'Hotteok' },
      { nameEnglish: 'Naengmyeon', nameLocal: '냉면', nameRomanized: 'Naengmyeon' },
      { nameEnglish: 'Samgyetang', nameLocal: '삼계탕', nameRomanized: 'Samgyetang' },
      { nameEnglish: 'Doenjang Jjigae', nameLocal: '된장찌개', nameRomanized: 'Doenjang Jjigae' },
      { nameEnglish: 'Galbi', nameLocal: '갈비', nameRomanized: 'Galbi' },
      { nameEnglish: 'Kimchi Bokkeumbap', nameLocal: '김치볶음밥', nameRomanized: 'Kimchi Bokkeumbap' },
      { nameEnglish: 'Mandu', nameLocal: '만두', nameRomanized: 'Mandu' },
      { nameEnglish: 'Budae Jjigae', nameLocal: '부대찌개', nameRomanized: 'Budae Jjigae' },
      { nameEnglish: 'Gamjatang', nameLocal: '감자탕', nameRomanized: 'Gamjatang' },
      { nameEnglish: 'Gimbap', nameLocal: '김밥', nameRomanized: 'Gimbap' },
      { nameEnglish: 'Ojingeo Bokkeum', nameLocal: '오징어볶음', nameRomanized: 'Ojingeo Bokkeum' },
    ],
  },
  japanese: {
    country: 'Japan',
    dishes: [
      { nameEnglish: 'Ramen', nameLocal: 'ラーメン', nameRomanized: 'Ramen' },
      { nameEnglish: 'Tonkatsu', nameLocal: 'とんかつ', nameRomanized: 'Tonkatsu' },
      { nameEnglish: 'Sushi', nameLocal: '寿司', nameRomanized: 'Sushi' },
      { nameEnglish: 'Tempura', nameLocal: '天ぷら', nameRomanized: 'Tempura' },
      { nameEnglish: 'Okonomiyaki', nameLocal: 'お好み焼き', nameRomanized: 'Okonomiyaki' },
      { nameEnglish: 'Gyudon', nameLocal: '牛丼', nameRomanized: 'Gyūdon' },
      { nameEnglish: 'Udon', nameLocal: 'うどん', nameRomanized: 'Udon' },
      { nameEnglish: 'Soba', nameLocal: 'そば', nameRomanized: 'Soba' },
      { nameEnglish: 'Takoyaki', nameLocal: 'たこ焼き', nameRomanized: 'Takoyaki' },
      { nameEnglish: 'Katsu Curry', nameLocal: 'カツカレー', nameRomanized: 'Katsu Karē' },
      { nameEnglish: 'Yakitori', nameLocal: '焼き鳥', nameRomanized: 'Yakitori' },
      { nameEnglish: 'Gyoza', nameLocal: '餃子', nameRomanized: 'Gyōza' },
      { nameEnglish: 'Sashimi', nameLocal: '刺身', nameRomanized: 'Sashimi' },
      { nameEnglish: 'Miso Soup', nameLocal: '味噌汁', nameRomanized: 'Misoshiru' },
      { nameEnglish: 'Onigiri', nameLocal: 'おにぎり', nameRomanized: 'Onigiri' },
      { nameEnglish: 'Karaage', nameLocal: '唐揚げ', nameRomanized: 'Karaage' },
      { nameEnglish: 'Sukiyaki', nameLocal: 'すき焼き', nameRomanized: 'Sukiyaki' },
      { nameEnglish: 'Shabu-shabu', nameLocal: 'しゃぶしゃぶ', nameRomanized: 'Shabu-shabu' },
      { nameEnglish: 'Unagi Don', nameLocal: 'うな丼', nameRomanized: 'Unadon' },
      { nameEnglish: 'Oyakodon', nameLocal: '親子丼', nameRomanized: 'Oyakodon' },
      { nameEnglish: 'Curry Rice', nameLocal: 'カレーライス', nameRomanized: 'Karē Raisu' },
      { nameEnglish: 'Edamame', nameLocal: '枝豆', nameRomanized: 'Edamame' },
      { nameEnglish: 'Nikujaga', nameLocal: '肉じゃが', nameRomanized: 'Nikujaga' },
      { nameEnglish: 'Tamagoyaki', nameLocal: '卵焼き', nameRomanized: 'Tamagoyaki' },
      { nameEnglish: 'Matcha Parfait', nameLocal: '抹茶パフェ', nameRomanized: 'Matcha Pafe' },
    ],
  },
  thai: {
    country: 'Thailand',
    dishes: [
      { nameEnglish: 'Pad Thai', nameLocal: 'ผัดไทย', nameRomanized: 'Phat Thai' },
      { nameEnglish: 'Green Curry', nameLocal: 'แกงเขียวหวาน', nameRomanized: 'Kaeng Khiao Wan' },
      { nameEnglish: 'Tom Yum Goong', nameLocal: 'ต้มยำกุ้ง', nameRomanized: 'Tom Yam Kung' },
      { nameEnglish: 'Som Tum', nameLocal: 'ส้มตำ', nameRomanized: 'Som Tam' },
      { nameEnglish: 'Massaman Curry', nameLocal: 'แกงมัสมั่น', nameRomanized: 'Kaeng Matsaman' },
      { nameEnglish: 'Pad See Ew', nameLocal: 'ผัดซีอิ๊ว', nameRomanized: 'Phat Si-io' },
      { nameEnglish: 'Khao Pad', nameLocal: 'ข้าวผัด', nameRomanized: 'Khao Phat' },
      { nameEnglish: 'Larb', nameLocal: 'ลาบ', nameRomanized: 'Lap' },
      { nameEnglish: 'Pad Kra Pao', nameLocal: 'ผัดกระเพรา', nameRomanized: 'Phat Kaphrao' },
      { nameEnglish: 'Tom Kha Gai', nameLocal: 'ต้มข่าไก่', nameRomanized: 'Tom Kha Kai' },
      { nameEnglish: 'Red Curry', nameLocal: 'แกงเผ็ด', nameRomanized: 'Kaeng Phet' },
      { nameEnglish: 'Mango Sticky Rice', nameLocal: 'ข้าวเหนียวมะม่วง', nameRomanized: 'Khao Niao Mamuang' },
      { nameEnglish: 'Satay', nameLocal: 'สะเต๊ะ', nameRomanized: 'Sate' },
      { nameEnglish: 'Panang Curry', nameLocal: 'พะแนง', nameRomanized: 'Phanaeng' },
      { nameEnglish: 'Kai Med Ma Muang', nameLocal: 'ไก่เม็ดมะม่วง', nameRomanized: 'Kai Met Mamuang' },
      { nameEnglish: 'Gaeng Som', nameLocal: 'แกงส้ม', nameRomanized: 'Kaeng Som' },
      { nameEnglish: 'Pad Pak Ruam', nameLocal: 'ผัดผักรวม', nameRomanized: 'Phat Phak Ruam' },
      { nameEnglish: 'Khao Soi', nameLocal: 'ข้าวซอย', nameRomanized: 'Khao Soi' },
      { nameEnglish: 'Tod Mun Pla', nameLocal: 'ทอดมันปลา', nameRomanized: 'Thot Man Pla' },
      { nameEnglish: 'Pla Rad Prik', nameLocal: 'ปลาราดพริก', nameRomanized: 'Pla Rat Phrik' },
      { nameEnglish: 'Gaeng Keow Wan Gai', nameLocal: 'แกงเขียวหวานไก่', nameRomanized: 'Kaeng Khiao Wan Kai' },
      { nameEnglish: 'Yam Woon Sen', nameLocal: 'ยำวุ้นเส้น', nameRomanized: 'Yam Wunsen' },
      { nameEnglish: 'Pad Woon Sen', nameLocal: 'ผัดวุ้นเส้น', nameRomanized: 'Phat Wunsen' },
      { nameEnglish: 'Kai Jeow', nameLocal: 'ไข่เจียว', nameRomanized: 'Khai Chiao' },
      { nameEnglish: 'Boat Noodles', nameLocal: 'ก๋วยเตี๋ยวเรือ', nameRomanized: 'Kuai Tiao Ruea' },
    ],
  },
  vietnamese: {
    country: 'Vietnam',
    dishes: [
      { nameEnglish: 'Pho', nameLocal: 'Phở', nameRomanized: 'Phở' },
      { nameEnglish: 'Banh Mi', nameLocal: 'Bánh mì', nameRomanized: 'Bánh Mì' },
      { nameEnglish: 'Bun Cha', nameLocal: 'Bún chả', nameRomanized: 'Bún Chả' },
      { nameEnglish: 'Goi Cuon', nameLocal: 'Gỏi cuốn', nameRomanized: 'Gỏi Cuốn' },
      { nameEnglish: 'Com Tam', nameLocal: 'Cơm tấm', nameRomanized: 'Cơm Tấm' },
      { nameEnglish: 'Bun Bo Hue', nameLocal: 'Bún bò Huế', nameRomanized: 'Bún Bò Huế' },
      { nameEnglish: 'Banh Xeo', nameLocal: 'Bánh xèo', nameRomanized: 'Bánh Xèo' },
      { nameEnglish: 'Cao Lau', nameLocal: 'Cao lầu', nameRomanized: 'Cao Lầu' },
      { nameEnglish: 'Mi Quang', nameLocal: 'Mì Quảng', nameRomanized: 'Mì Quảng' },
      { nameEnglish: 'Bun Rieu', nameLocal: 'Bún riêu', nameRomanized: 'Bún Riêu' },
      { nameEnglish: 'Bo Luc Lac', nameLocal: 'Bò lúc lắc', nameRomanized: 'Bò Lúc Lắc' },
      { nameEnglish: 'Cha Ca', nameLocal: 'Chả cá', nameRomanized: 'Chả Cá' },
      { nameEnglish: 'Nem Ran', nameLocal: 'Nem rán', nameRomanized: 'Nem Rán' },
      { nameEnglish: 'Xoi', nameLocal: 'Xôi', nameRomanized: 'Xôi' },
      { nameEnglish: 'Hu Tieu', nameLocal: 'Hủ tiếu', nameRomanized: 'Hủ Tiếu' },
      { nameEnglish: 'Banh Cuon', nameLocal: 'Bánh cuốn', nameRomanized: 'Bánh Cuốn' },
      { nameEnglish: 'Pho Bo', nameLocal: 'Phở bò', nameRomanized: 'Phở Bò' },
      { nameEnglish: 'Pho Ga', nameLocal: 'Phở gà', nameRomanized: 'Phở Gà' },
      { nameEnglish: 'Ca Kho To', nameLocal: 'Cá kho tộ', nameRomanized: 'Cá Kho Tộ' },
      { nameEnglish: 'Bun Thit Nuong', nameLocal: 'Bún thịt nướng', nameRomanized: 'Bún Thịt Nướng' },
      { nameEnglish: 'Che', nameLocal: 'Chè', nameRomanized: 'Chè' },
      { nameEnglish: 'Banh Bao', nameLocal: 'Bánh bao', nameRomanized: 'Bánh Bao' },
      { nameEnglish: 'Bo Kho', nameLocal: 'Bò kho', nameRomanized: 'Bò Kho' },
      { nameEnglish: 'Canh Chua', nameLocal: 'Canh chua', nameRomanized: 'Canh Chua' },
      { nameEnglish: 'Banh Trang Nuong', nameLocal: 'Bánh tráng nướng', nameRomanized: 'Bánh Tráng Nướng' },
    ],
  },
  malaysian: {
    country: 'Malaysia',
    dishes: [
      { nameEnglish: 'Nasi Lemak', nameLocal: 'Nasi Lemak', nameRomanized: 'Nasi Lemak' },
      { nameEnglish: 'Char Kway Teow', nameLocal: 'Char Kway Teow', nameRomanized: 'Char Kway Teow' },
      { nameEnglish: 'Laksa', nameLocal: 'Laksa', nameRomanized: 'Laksa' },
      { nameEnglish: 'Satay', nameLocal: 'Satay', nameRomanized: 'Satay' },
      { nameEnglish: 'Roti Canai', nameLocal: 'Roti Canai', nameRomanized: 'Roti Canai' },
      { nameEnglish: 'Rendang', nameLocal: 'Rendang', nameRomanized: 'Rendang' },
      { nameEnglish: 'Nasi Goreng', nameLocal: 'Nasi Goreng', nameRomanized: 'Nasi Goreng' },
      { nameEnglish: 'Mee Goreng', nameLocal: 'Mee Goreng', nameRomanized: 'Mee Goreng' },
      { nameEnglish: 'Hainanese Chicken Rice', nameLocal: 'Nasi Ayam Hainan', nameRomanized: 'Nasi Ayam Hainan' },
      { nameEnglish: 'Bak Kut Teh', nameLocal: 'Bak Kut Teh', nameRomanized: 'Bak Kut Teh' },
      { nameEnglish: 'Hokkien Mee', nameLocal: 'Hokkien Mee', nameRomanized: 'Hokkien Mee' },
      { nameEnglish: 'Rojak', nameLocal: 'Rojak', nameRomanized: 'Rojak' },
      { nameEnglish: 'Cendol', nameLocal: 'Cendol', nameRomanized: 'Cendol' },
      { nameEnglish: 'Murtabak', nameLocal: 'Murtabak', nameRomanized: 'Murtabak' },
      { nameEnglish: 'Nasi Kandar', nameLocal: 'Nasi Kandar', nameRomanized: 'Nasi Kandar' },
      { nameEnglish: 'Curry Mee', nameLocal: 'Curry Mee', nameRomanized: 'Curry Mee' },
      { nameEnglish: 'Wonton Mee', nameLocal: 'Wonton Mee', nameRomanized: 'Wonton Mee' },
      { nameEnglish: 'Asam Laksa', nameLocal: 'Asam Laksa', nameRomanized: 'Asam Laksa' },
      { nameEnglish: 'Ayam Percik', nameLocal: 'Ayam Percik', nameRomanized: 'Ayam Percik' },
      { nameEnglish: 'Ikan Bakar', nameLocal: 'Ikan Bakar', nameRomanized: 'Ikan Bakar' },
      { nameEnglish: 'Nasi Kerabu', nameLocal: 'Nasi Kerabu', nameRomanized: 'Nasi Kerabu' },
      { nameEnglish: 'Apam Balik', nameLocal: 'Apam Balik', nameRomanized: 'Apam Balik' },
      { nameEnglish: 'Kuih', nameLocal: 'Kuih', nameRomanized: 'Kuih' },
      { nameEnglish: 'Prawn Mee', nameLocal: 'Prawn Mee', nameRomanized: 'Prawn Mee' },
      { nameEnglish: 'Tosai', nameLocal: 'Tosai', nameRomanized: 'Tosai' },
    ],
  },
}
